### ISSUE TITLE
Discussion: `custom_app` branch

### ISSUE THREAD

**Issue by alok** [jalvesaq/vimcmdline#13]
@jalvesaq  @1o0ko

Feel free to close this/move to a more appropriate section, but I figured this would be the best place to discuss the commit to allow different REPLs.

It works for haskell, but (i)python support is broken. I suspect you will have to use paste mode (%cpaste), and you may want to see how [vim-slime](https://github.com/jpalardy/vim-slime) does it.

They have good handling for python but don't open the repl for you.

**Comment by jalvesaq** [comment]
Note: I almost never use any REPL other than R. That is, I almost never use vimcmdline. That said, I installed and tested ipython in a Neovim buffer, and noted that it has Normal and Insert modes, like Vim.
I noted this because when sending `%cpaste` ipython actually only "receives" `ste`, as Vim would do if it was in Normal mode.

If I send to ipython a line containing only the letter `a`, it enters Insert mode and, then, I can send commands normally. If it is not in Insert mode, nothing works, including sending
```
%cpaste -q
The_Python_line
--
```

So, it seems that users have to make sure that ipython is in Insert mode before sending commands to it.

**Comment by alok** [comment]
I use it in emacs mode actually, since nested modes are a pain. In emacs mode, I still run into issues.

**Comment by jalvesaq** [comment]
Is https://github.com/ivanov/vim-ipython a better alternative than vimcmdline for ipython? I did not install it.

**Comment by 1o0ko** [comment]
@jalvesaq [vim-ipython ](https://github.com/ivanov/vim-ipython) is a little cumbersome. It requires you to open ipython kernel/console beforehand.

**Comment by alok** [comment]
I've not used [vim-ipython](https://github.com/ivanov/vim-ipython), so I can't really speak to that.

**Comment by jalvesaq** [comment]
The incompatibility between vimcmdline and ipython was discussed at https://github.com/jalvesaq/vimcmdline/issues/18, and there is no solution for it (so, I'm closing this issue).
