### ISSUE TITLE
Settings for line ending character

### ISSUE THREAD

**Issue by adrianadermon** [jalvesaq/vimcmdline#44]
As you know, I've been trying to figure out how to get line endings to work correctly on Windows. To experiment with this, I can set cmdline_nl to different values in Neovim interactively. But whenever I try to change this setting in my settings files, it seems to get overridden by the plugin settings. 

Would it be possible to expose per-filetype line ending settings to the user in a similar way as with the cmdline_app option? This would make it easier to customize my setup.

**Comment by jalvesaq** [comment]
What exactly is the command that you are using to set `b:cmdline_nl` in the vimrc/init.vim? I think this should work:

```vim
autocmd FileType python let b:cmdline_n = "\r\n"
```
> Would it be possible to expose per-filetype line ending settings to the user in a similar way as with the cmdline_app option?

It would be possible, but I think it would not be the correct design to adopt because the choice of newline character is not a matter of taste: there is only one correct value for each case. This is a programming task, and should not be delegated to users. Vimcmdline should be programmed to choose the correct value in each case.

**Comment by adrianadermon** [comment]
Yes, that works. I tried setting it in the ftplugin files, which didn't work.

> It would be possible, but I think it would not be the correct design to adopt because the choice of newline character is not a matter of taste: there is only one correct value for each case.

That makes sense.
