### ISSUE TITLE
Feature request: output in source buffer instead of terminal

### ISSUE THREAD

**Issue by seb-mueller** [jalvesaq/vimcmdline#49]
Hi,

Would it be possible to direct the output into the buffer it was called from instead of the terminal?
This would be similar to Nvim-R <localleader>o as below:

https://github.com/jalvesaq/Nvim-R/blob/100ba75258cf7f5d0033a8b3c2aabbb999bb162f/doc/Nvim-R.txt#L480

Anyway, fantastic work! Really appreciate this plugin on a daily basis.

**Comment by jalvesaq** [comment]
In Nvim-R, the command to be executed is sent to nvimcom which executes the command in the running R and saves the output in a temporary file:

![nvimrcom](https://raw.githubusercontent.com/jalvesaq/Nvim-R/master/nvimrcom.png)

It's not possible to do the same in vimcmdline because there is no equivalent to nvimcom loaded by the supported interpreters.

**Comment by seb-mueller** [comment]
Thanks for the heads-up! Well it's a pretty nifty plug-in regardless! Cheers

**Comment by seb-mueller** [comment]
Since this is not possible the vimcmdline-way, I've found an vim native workaround which might do the rick for some cases:
Say you have a buffer with the following contend:

```
Today is:
date
```

And you want to evaluate the 2nd line (data) and have the output replacing it, you just evaluate:
`:.!sh` on that line resulting in:

```
Today is:
Wed  5 Dec 10:05:17 GMT 2018
```

This can of course be extended to ranges, e.g. evaluating the current selected lines `'<,'>!sh` or map it to a shortcut `nmap <leader>o :.!sh<CR>` etc.

See the manual for further reading:
https://vim-jp.org/vimdoc-en/change.html#:range!
