### ISSUE TITLE
FR: Can we open an external terminal in vim ?

### ISSUE THREAD

**Issue by statquant** [jalvesaq/vimcmdline#7]
Could we get the same feature that we get in vim-r-plugin:  an option to open an external  terminal instead of a tmux pane ?

**Comment by jalvesaq** [comment]
Please, put in your `~/.vimrc` or `~/.config/nvim/init.vim`:

```
let R_in_buffer = 0
let R_tmux_split = 0
let R_applescript = 0
```

Not all options are required in every combination of operating system and editor (Vim or Neovim), but it does not hurt to put them all in the vimrc.

**Comment by statquant** [comment]
Sorry that does not seem to be working.
Are we speaking vimcmdline here ?
I would do

$tmux
$vim test.q #I added support
=> from within vim MapLeader+s (or what I have remaped to)
=> I should get an EXTERNAL terminal (not a tmux buffer) but I get an horizontal split

Is that correct ?

If I try to start it without tmux I get "Unknown function VimCmdLineStartApp" 
I also tried with r (I also have your plugin) and it works with/without tmux

**Comment by jalvesaq** [comment]
Sorry, I thought it was about Nvim-R.

To start the interpreter in an external terminal emulator, I would have to make adjustments to the script [extern_term.vim](https://github.com/jalvesaq/Nvim-R/blob/master/R/extern_term.vim). I am not going to do this now because I prefer to run the interpreter in a Neovim buffer to get colored output, but we may let the issue open. Perhaps someone else does a pull request for this...
