### ISSUE TITLE
This is not an issue, but I think open the bash terminal whatever the filetype is be a good idea.

### ISSUE THREAD

**Issue by MuhammadMuradG** [jalvesaq/vimcmdline#92]
Hi Jakson,

First of all, I would like to thank you for this great Plugin. 

The suggestion is when you are working on a large projects it would be very stressful and confused to leave the workspace and open a new Terminal to do some related work like updating or installing a some components etc. In most popular IDEs like Atom and VSCode you can open a Terminal in the workspace to accomplish these tasks without leaving the workspace. So I think it would be a great addition to this Plugin if it was applied. For example when working on a Django project, what I suggest is something like that:
![Screenshot for the suggestion](https://user-images.githubusercontent.com/50509521/80299761-8716b080-8786-11ea-9051-57e03445011f.png)

**Comment by jalvesaq** [comment]
I always have only one terminal window open. It starts running bash within a Tmux session and usually I keep at least two Tmux tabs open: one for the main project I'm working on at the moment and the other to check emails, install packages, etc...

If the preference is for running a built-in terminal for general tasks, then, this feature has to be provided by Vim/Neovim because this is needed regardless of what is being edited, and both Vim and Neovim already have the `:terminal` command. Perhaps what you are missing is a shortcut for opening a terminal running bash, and this could be set in your vimrc/init.vim. Something like:

```vim
nmap <silent><Leader>t :belowright 10split +terminal<CR>
```

**Comment by MuhammadMuradG** [comment]
Thank you for your prompt reply and guidance. I will use what you are using It is exactly what I want.
